### ISSUE TITLE
Fork of example.net ?

### ISSUE THREAD

**Issue by SomethingGeneric** [Richienb/Example#2]
I'm not 100% on this, but this seems to be a fork of the website running on example.net. I'm sure you're not violating their license, but might be nice to credit if it is??

**Comment by Richienb** [comment]
@SomethingGeneric To resolve this issue, I've referenced IANA Example Domains in the LICENSE in https://github.com/Richienb/example-web/commit/cf6dfc59039f5a686e5c79bc7b9b614c41b08663.
